"""add remark in user table

Revision ID: 5e7e6e6e5e1f
Revises: f9eb03614a7f
Create Date: 2025-10-22 00:31:40.870457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7e6e6e5e1f'
down_revision: Union[str, Sequence[str], None] = 'f9eb03614a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remark', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remark')
    # ### end Alembic commands ###
