"""change size of remark in user table

Revision ID: 73258f89d698
Revises: 5e7e6e6e5e1f
Create Date: 2025-10-22 01:08:49.986053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '73258f89d698'
down_revision: Union[str, Sequence[str], None] = '5e7e6e6e5e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'remark',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'remark',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
